require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '13.0'

install! 'cocoapods', :deterministic_uuids => false

target 'Newsfeed' do
  # use_frameworks!
  pod 'FlipperKit', '0.93.0', :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitLayoutPlugin', '0.93.0', :configuration => 'Debug'
  pod 'FlipperKit/SKIOSNetworkPlugin', '0.93.0', :configuration => 'Debug'

  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false
  )

  target 'NewsfeedTests' do
    inherit! :complete
  end

  $static_framework = ['FlipperKit', 'Flipper', 'Flipper-Folly',
    'CocoaAsyncSocket', 'ComponentKit', 'DoubleConversion',
    'glog', 'Flipper-PeerTalk', 'Flipper-RSocket', 'Yoga', 'YogaKit',
    'CocoaLibEvent', 'OpenSSL-Universal', 'boost-for-react-native']
 
  pre_install do |installer|
    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
    installer.pod_targets.each do |pod|
      if $static_framework.include?(pod.name)
        def pod.build_type;
          Pod::BuildType.static_library
        end
      end
    end
  end
end
